python embed_script.py src/lua/run.lua src/lua/run.hh scriptRunLua
python embed_script.py src/lua/auxiliary.lua src/lua/auxiliary.hh scriptAuxLua
python embed_script.py src/lua/event.lua src/lua/event.hh scriptEventLua
python embed_script.py src/lua/math.lua src/lua/math.hh scriptMathLua
python embed_script.py src/lua/shader.lua src/lua/shader.hh scriptShaderLua
python embed_script.py src/lua/class.lua src/lua/class.hh scriptClassLua
python embed_script.py src/lua/input.lua src/lua/input.hh scriptInputLua
python embed_script.py src/lua/set.lua src/lua/set.hh scriptSetLua
python embed_script.py src/lua/thing.lua src/lua/thing.hh scriptThingLua
