python embed_script.py src/lua/run.lua src/lua/run.hh scriptrunlua
python embed_script.py src/lua/auxiliary.lua src/lua/auxiliary.hh scriptauxlua
python embed_script.py src/lua/event.lua src/lua/event.hh scripteventlua
python embed_script.py src/lua/math.lua src/lua/math.hh scriptmathlua
python embed_script.py src/lua/shader.lua src/lua/shader.hh scriptshaderlua
python embed_script.py src/lua/class.lua src/lua/class.hh scriptclasslua
python embed_script.py src/lua/input.lua src/lua/input.hh scriptinputlua
python embed_script.py src/lua/set.lua src/lua/set.hh scriptsetlua
python embed_script.py src/lua/thing.lua src/lua/thing.hh scriptthinglua
